# Generated by Django 3.0.3 on 2020-09-01 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0002_auto_20200901_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='thetare',
            name='user',
            field=models.OneToOneField(default='am1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
