# Generated by Django 3.0.3 on 2020-09-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200901_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thetare',
            name='user',
        ),
    ]
